apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t6rcnxf04-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:eb86adf1d8bb724bee755f2f712a4c52edc4520b@sha256:f0a89e37bb28131b1e363354e762652aed1bb4ace50873a1253a923d52bff7e3
          name: container-image
